version: "3"

services:
  wechatbot:
    build: .
    container_name: wechatbot
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./tmp:/tmp
    depends_on:
      - redis
    environment:
      - TZ=Asia/Shanghai
  redis:
    image: "redis:6.0.10-alpine"
    container_name: redis
    restart: always
    volumes:
      - ./persist:/data
    ports:
      - "16379:6379"
